name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger main build workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                build_variant: 'runtime'
              }
            })
            
      - name: Note about nightly builds
        run: |
          echo "Nightly builds now use prebuilt components from components-latest release"
          echo "This ensures consistent and fast builds every night"
          echo "Components are rebuilt weekly or when patches are updated"